var data = [
["Bad","Good"],
["Mildly addictive","Highly addictive"],
["Hot","Cold"],
["Normal","Weird"],
["Colorless","Colorful"],
["Low calorie","High calorie"],
["Feels bad","Feels good"],
["Inessential","Essential"],
["Cheap","Expensive"],
["Underrated weapon","Overrated weapon"],
["Rare","Common"],
["Easy subject","Hard subject"],
["Unknown","Famous"],
["Difficult to use","Easy to use"],
["Tired","Wired"],
["Dirty","Clean"],
["Requires luck","Requires skill"],
["Flavorless","Flavorful"],
["Boring topic","Fascinating topic"],
["Bad actor","Good actor"],
["Basic","Hipster"],
["Dangerous job","Safe job"],
["Fantasy","Sci-Fi"],
["Casual","Formal"],
["Underpaid","Overpaid"],
["Dry","Wet"],
["Underrated skill","Overrated skill"],
["Forbidden","Encouraged"],
["Sad song","Happy song"],
["Fragile","Durable"],
["Geek","Dork"],
["Good","Evil"],
["Worst day of the year","Best day of the year"],
["Bad habit","Good habit"],
["Cat person","Dog person"],
["Untalented","Talented"],
["Dark","Light"],
["Underrated actor","Overrated actor"],
["Hard to find","Easy to find"],
["Ugly man","Beautiful man"],
["Hard to remember","Easy to remember"],
["Lowbrow","Highbrow"],
["Unhealthy","Healthy"],
["Historically important","Historically irrelevant"],
["Hairless","Hairy"],
["Inflexible","Flexible"],
["Normal pet","Exotic pet"],
["Introvert","Extrovert"],
["Book was better","Movie was better"],
["Bad movie","Good movie"],
["Ugly","Beautiful"],
["Happens slowly","Happens suddenly"],
["Job","Career"],
["Loved","Hated"],
["The Light Side of the Force","The Dark Side of the Force"],
["Bad pizza topping","Good pizza topping"],
["Dystopia","Utopia"],
["Mature person","Immature person"],
["Underrated thing to own","Overrated thing to own"],
["Mean person","Nice person"],
["Action movie","Adventure movie"],
["Mental activity","Physical activity"],
["Uncontroversial topic","Controversial topic"],
["Need","Want"],
["Dry food","Wet food"],
["Normal thing to own","Weird thing to own"],
["Straight","Curvy"],
["Bad person","Good person"],
["80s","90s"],
["Ethical to eat","Unethical to eat"],
["Movie","Film"],
["Optional","Mandatory"],
["Underrated letter of the alphabet","Overrated letter of the alphabet"],
["Ordinary","Extraordinary"],
["Hard to pronounce","Easy to pronounce"],
["Low quality","High quality"],
["Plain","Fancy"],
["Has a bad reputation","Has a good reputation"],
["Poorly made","Well made"],
["Not a sandwich","A sandwich"],
["Quiet place","Loud place"],
["Comedy","Drama"],
["Dangerous","Safe"],
["Culturally significant","Culturally insignificant"],
["Replaceable","Irreplaceable"],
["Worst athlete of all time","Greatest athlete of all time"],
["Role model","Bad influence"],
["Useless major","Useful major"],
["Peaceful","Warlike"],
["Underrated movie","Overrated movie"],
["Rough","Smooth"],
["Bad for you","Good for you"],
["Round","Pointy"],
["Proof that God exists","Proof that God doesn’t exist"],
["Sad movie","Happy movie"],
["Waste of time","Good use of time"],
["Scary animal","Nice animal"],
["Mainstream","Niche"],
["Short lived","Long lived"],
["Nobody does it","Everybody does it"],
["Smells bad","Smells good"],
["Star Wars","Star Trek"],
["Snack","Meal"],
["Least evil company","Most evil company"],
["Soft","Hard"],
["Sustenance","Haute cuisine"],
["Square","Round"],
["Better hot","Better cold"],
["Stupid","Brilliant"],
["Artisanal","Mass produced"],
["Bad superpower","Good superpower"],
["Ineffective","Effective"],
["Unbelievable","Believable"],
["Trashy","Classy"],
["Temporary","Permanent"],
["Looks like a person","Doesn't look like a person"],
["Tastes bad","Tastes good"],
["Sport","Game"],
["Uncool","Cool"],
["Worst living person","Greatest living person"],
["Underrated","Overrated"],
["Messy food","Clean food"],
["Unethical","Ethical"],
["Bad gift","Good gift"],
["Unfashionable","Fashionable"],
["Freedom fighter","Terrorist"],
["Unforgiveable","Forgiveable"],
["Failure","Masterpiece"],
["Harmless","Harmful"],
["Gryffindor","Slytherin"],
["Unhygienic","Hygienic"],
["Bad music","Good music"],
["Useless","Useful"],
["Movie that Godzilla would ruin","Movie that Godzilla would improve"],
["Unimportant","Important"],
["Easy to spell","Hard to spell"],
["Vice","Virtue"],
["Underrated musician","Overrated musician"],
["Unpopular activity","Popular activity"],
["Divided","Whole"],
["Unreliable","Reliable"],
["Easy to kill","Hard to kill"],
["Unstable","Stable"],
["Round animal","Pointy animal"],
["Bad TV show","Good TV show"],
["Traditionally masculine","Traditionally feminine"],
["Useless body part","Useful body part"],
["Fad","Classic"],
["Weak","Strong"],
["Disgusting cereal","Delicious cereal"],
["Useless invention","Useful invention"],
["Liberal","Conservative"],
["Unpopular","Popular"],
["Friend","Enemy"],
["Boring","Exciting"],
["Smelly in a bad way","Smelly in a good way"],
["Villain","Hero"],
["Underrated thing to do","Overrated thing to do"],
["Useless in an emergency","Useful in an emergency"],
["For kids","For adults"],
["Wise","Intelligent"],
["Easy to do","Hard to do"],
["Worthless","Priceless"],
["Nature","Nurture"],
["Dictatorship","Democracy"],
["Normal greeting","Weird greeting"],
["Dog name","Cat name"],
["Non-partisan","Partisan"],
["Limited","Infinite"],
["Casual event","Formal event"],
["Bad investment","Good investment"],
["Small talk","Heavy topic"],
["Mild","Spicy"],
["Religious","Sacrilegious"],
["Not art","Art"],
["Popular","Elitist"],
["Out of control","In control"],
["Quiet","Loud"],
["Secret","Public knowledge"],
["Too small","Too big"],
["Short","Long"],
["Worst year in history","Best year in history"],
["Socialist","Capitalist"],
["Little known fact","Well known fact"],
["Stationary","Mobile"],
["Local issue","Global issue"],
["Talent","Skill"],
["Worst era to time travel","Best era to time travel"],
["The worst","The best"],
["Small number","Large number"],
["Old fashioned","Avant garde"],
["Ugly word","Beautiful word"],
["Small","Tiny"],
["Unnatural","Natural"],
["Genuine person","Phony person"],
["Derivative","Original"],
["Benefits you","Benefits everyone"],
["Powerless","Powerful"],
["Fruit","Vegetable"],
["Science","Pseudoscience"],
["Funny topic","Serious topic"],
["Guilty pleasure","Actually just bad"],
["Gossip","News"],
["Hard to sit on","Easy to sit on"],
["Not enough","Too much"],
["Horizontal","Vertical"],
["Unscented","Scented"],
["Huggable","Not huggable"],
["Heterogeneous","Homogenous"],
["Inclusive","Exclusive"],
["Bad dog breed","Good dog breed"],
["Art","Commerce"],
["One hit wonder","Pop icon"],
["Bad advice","Good advice"],
["Bad candy","Good candy"],
["Traditional","Radical"],
["Bad mouthfeel","Good mouthfeel"],
["Illegal","Legal"],
["Deep thought","Shallow thought"],
["Bad school","Good school"],
["Never on time","Always on time"],
["Won't live to 100","Will live to 100"],
["Bad Disney character","Good Disney character"],
["Bad president","Good president"],
["Famous","Infamous"],
["Least powerful god","Most powerful god"],
["Boring person","Fun person"],
["Underrated book","Overrated book"],
["Conventional wisdom","Fringe belief"],
["Worst chore","Best chore"],
["Endangered species","Overpopulated species"],
["Blue","Green"],
["Thrilling","Terrifying"],
["Nerd","Jock"],
["Expected","Unexpected"],
["Person you could beat up","Person who’d beat you up"],
["Unreasonable phobia","Reasonable phobia"],
["Underrated game","Overrated game"],
["Bad smell","Good smell"],
["Underrated holiday","Overrated holiday"],
["Underrated food","Overrated food"],
["Underrated TV show","Overrated TV show"],
["Underrated city","Overrated city"],
["Underrated sport","Overrated sport"],
["Bad cartoon character","Good cartoon character"],
["Bad band name","Good band name"],
["Bad breakfast food","Good breakfast food"],
["Bad ice cream flavor","Good ice cream flavor"],
["Bad vacation spot","Good vacation spot"],
["Bad first date idea","Good first date idea"],
["Bad name for a pet","Good name for a pet"],
["Bad excuse","Good excuse"],
["Bad song to sing at karaoke","Good song to sing at karaoke"],
["Bad time to sleep","Good time to sleep"],
["Lazy","Hardworking"],
["Cozy","Cold and clinical"],
["Awkward","Smooth"],
["Embarrassing","Impressive"],
["Cheesy","Sophisticated"],
["Wholesome","Edgy"],
["Serious","Silly"],
["Slow","Fast"],
["Soothing","Annoying"],
["Cute","Menacing"],
["Overhyped","Underhyped"],
["Easy to cook","Hard to cook"],
["Worth waiting in line for","Not worth waiting in line for"],
["Mostly luck","Mostly skill"],
["Acquired taste","Instantly likeable"],
["Easy to learn","Hard to master"],
["Useful in a zombie apocalypse","Useless in a zombie apocalypse"],
["Embarrassing to listen to","Cool to listen to"],
["Morning thing","Night thing"],
["Summer activity","Winter activity"],
["Better alone","Better with friends"],
["Crunchy","Chewy"],
["Sweet","Savory"],
["Quick fix","Long-term solution"],
["Easy to forgive","Hard to forgive"],
["Over-the-top","Understated"],
["Best time to be alive","Worst time to be alive"],
["Rude","Polite"],
["Nostalgic","Futuristic"],
["Wasteful","Efficient"]
];

